use_frameworks!

target 'SimpleKeyboard_Example' do
  pod 'SimpleKeyboard', :path => '../'

  target 'SimpleKeyboard_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
  pod 'Nimble', '~> 7.0.2'
  end
end
